### ISSUE TITLE
Cannot update a component (`Form`) while rendering a different component (`LexicalRichTextFieldComponent2`). 

### ISSUE THREAD

**Issue by johannesschaffer** [AlessioGr/payload-plugin-lexical#13]
`Warning: Cannot update a component (`Form`) while rendering a different component (`LexicalRichTextFieldComponent2`). To locate the bad setState() call inside `LexicalRichTextFieldComponent2`, follow the stack trace as described in https://reactjs.org/link/setstate-in-render`

This is logged in the browser console after using the editor in a fresh Collection. (As far as I'm aware) it doesn't break anything, just thought I'd let you know.

**Comment by AlessioGr** [comment]
> `Warning: Cannot update a component (`Form`) while rendering a different component (`LexicalRichTextFieldComponent2`). To locate the bad setState() call inside `LexicalRichTextFieldComponent2`, follow the stack trace as described in https://reactjs.org/link/setstate-in-render`
> 
> This is logged in the browser console after using the editor in a fresh Collection. (As far as I'm aware) it doesn't break anything, just thought I'd let you know.

Yep, I'm aware of that. But to be honest, I'm really not sure what exactly causes it. Would appreciate if anyone has some ideas what it could be!

**Comment by AlessioGr** [comment]
Hmm, testing it out currently, it only seems to happen during dev—not in production. Weird!

**Comment by AlessioGr** [comment]
@johannesschaffer just fixed this with #22 in v0.5.0 :)
