### ISSUE TITLE
required: true doesn't seem to work & cms thinks content has changed

### ISSUE THREAD

**Issue by johannesschaffer** [AlessioGr/payload-plugin-lexical#14]
Even if the editor is empty, still passes and lets me publish.
Additionally, on a blank page (without having writting anything inside the editor): If I reload, Payload warns me that content is gonna be lost. That's very likely also why it passes the "required: true" with nothing in the editor

**Comment by AlessioGr** [comment]
Just fixed that in v0.1.2!

**Comment by johannesschaffer** [comment]
Still doesn't quite work. As far as I can tell the "required" works now (however without showing where the error happend - you probably missed the error popup in your custom field), but a blank editor field added to a collection still makes payload thinks I have unsaved content (for comparison, adding an empty "text" field works like intended)
