### ISSUE TITLE
Changing the name of a link doesn't work

### ISSUE THREAD

**Issue by johannesschaffer** [AlessioGr/payload-plugin-lexical#20]
Reproduce: Paste or type in a link. Then try to change in the name in the resulting popup. Changing the URL works.
Furthermore, changing the name of the link by just editing the text in the editor directly (like it's don in the lexical playground) changes the name & link simulationsly to whatever is typed.

**Comment by AlessioGr** [comment]
Fixed in v0.1.3! Now it should work
